### ISSUE TITLE
Binaires in GitHub releases

### ISSUE THREAD

**Issue by garc33** [codestoryai/aide#997]
### Idea

Hello,
Would be great if IDE releases could be proposed with binaries into GitHub releases

**Comment by ghostwriternr** [comment]
Hey @garc33! Apologies, I'd missed this earlier. But all the releases are indeed already on GitHub releases at https://github.com/codestoryai/binaries, albeit on a different one. The reason for this is because we used to be closed sourced in the past, and thus needed a separate public repo where we could push the releases.
